// Mirror each project page's editable text into the media inbox as page.md,
// one per project folder, so the site can be copy-edited from plain files.
// The inbox routine applies edits back through the Studio API (idempotent —
// unchanged text produces no diff), then re-runs this script to refresh.
// Only fields present on a page are emitted: the apply path is replace-based
// and cannot create markup that is not there.
const path = require('path');
const fs = require('fs');
const { parseProjectHtml, rootProjectSlugs, workDir } = require('./server');

const inboxDir = process.env.RTFX_INBOX || 'E:\\rtfx-inbox';

function listProjectSlugs() {
  const work = fs.readdirSync(workDir).filter(d =>
    fs.existsSync(path.join(workDir, d, 'index.html')));
  const roots = rootProjectSlugs.filter(slug =>
    fs.existsSync(path.join(workDir, '..', slug, 'index.html')));
  return [...work, ...roots];
}

function pageMarkdown(project) {
  const lines = [
    `<!-- RTFX page text · ${project.slug} · regenerated by \`node studio/inbox-pages.js\` -->`,
    '<!-- Edit the text; keep the headings and the "- Key:" / "- filename:" line shapes.',
    '     The inbox routine applies changes back to the live page, then refreshes this',
    '     file. Only what appears here is editable this way. -->',
    '',
    `# ${project.title || project.slug}`
  ];
  const section = (heading, value) => {
    if (value) lines.push('', `## ${heading}`, value);
  };
  section('Tagline', project.tagline);
  const details = [
    ['Category', project.category],
    ['Location', project.location],
    ['Timeframe', project.timeframe],
    ['Role', project.role]
  ].filter(([, value]) => value);
  if (details.length) {
    lines.push('', '## Details');
    for (const [key, value] of details) lines.push(`- ${key}: ${value}`);
  }
  section('Lede', project.description);
  section('Challenge', project.challenge);
  section('Response', project.response);
  section('Outcome', project.outcome);
  for (const group of project.pageMedia) {
    const captioned = group.items.filter(item => item.filename);
    if (!captioned.length) continue;
    lines.push('', `## Captions — ${group.label}`);
    for (const item of captioned) lines.push(`- ${item.filename}: ${item.caption || ''}`);
  }
  return lines.join('\n') + '\n';
}

function main() {
  if (!fs.existsSync(inboxDir)) {
    console.error(`Inbox not found at ${inboxDir}`);
    process.exit(1);
  }
  let written = 0;
  for (const slug of listProjectSlugs()) {
    const project = parseProjectHtml(slug);
    if (!project) continue;
    const folder = path.join(inboxDir, slug);
    if (!fs.existsSync(folder)) fs.mkdirSync(folder, { recursive: true });
    fs.writeFileSync(path.join(folder, 'page.md'), pageMarkdown(project), 'utf8');
    written++;
  }
  console.log(`Wrote page.md for ${written} projects into ${inboxDir}`);
}

if (require.main === module) main();
module.exports = { pageMarkdown, listProjectSlugs };
