headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "E:\\Antigravity rtfx design system\\site"
publishOrigin = "config"
base = "E:\\Antigravity rtfx design system\\site"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/css/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/js/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=2592000"

[[headers]]
for = "/work/*/media/*"

[headers.values]
Cache-Control = "public, max-age=2592000"